spring:
  application:
    name: beebee-archives-thrift-provider-client

server:
  port: 10121

thrift:
  server:
    host: localhost
    port: 10141

# 禁止自动注册eureka，仅dev模式使用
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false