/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.quwan.beebee.param.archives;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-12-29")
public class ArchivesPushParam implements org.apache.thrift.TBase<ArchivesPushParam, ArchivesPushParam._Fields>, java.io.Serializable, Cloneable, Comparable<ArchivesPushParam> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ArchivesPushParam");

  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PUSH_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("pushNum", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField PUSH_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("pushType", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ArchivesPushParamStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ArchivesPushParamTupleSchemeFactory();

  public int userId; // required
  public int pushNum; // required
  public int pushType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_ID((short)1, "userId"),
    PUSH_NUM((short)2, "pushNum"),
    PUSH_TYPE((short)3, "pushType");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_ID
          return USER_ID;
        case 2: // PUSH_NUM
          return PUSH_NUM;
        case 3: // PUSH_TYPE
          return PUSH_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __USERID_ISSET_ID = 0;
  private static final int __PUSHNUM_ISSET_ID = 1;
  private static final int __PUSHTYPE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userId", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PUSH_NUM, new org.apache.thrift.meta_data.FieldMetaData("pushNum", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PUSH_TYPE, new org.apache.thrift.meta_data.FieldMetaData("pushType", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ArchivesPushParam.class, metaDataMap);
  }

  public ArchivesPushParam() {
  }

  public ArchivesPushParam(
    int userId,
    int pushNum,
    int pushType)
  {
    this();
    this.userId = userId;
    setUserIdIsSet(true);
    this.pushNum = pushNum;
    setPushNumIsSet(true);
    this.pushType = pushType;
    setPushTypeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ArchivesPushParam(ArchivesPushParam other) {
    __isset_bitfield = other.__isset_bitfield;
    this.userId = other.userId;
    this.pushNum = other.pushNum;
    this.pushType = other.pushType;
  }

  public ArchivesPushParam deepCopy() {
    return new ArchivesPushParam(this);
  }

  @Override
  public void clear() {
    setUserIdIsSet(false);
    this.userId = 0;
    setPushNumIsSet(false);
    this.pushNum = 0;
    setPushTypeIsSet(false);
    this.pushType = 0;
  }

  public int getUserId() {
    return this.userId;
  }

  public ArchivesPushParam setUserId(int userId) {
    this.userId = userId;
    setUserIdIsSet(true);
    return this;
  }

  public void unsetUserId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  /** Returns true if field userId is set (has been assigned a value) and false otherwise */
  public boolean isSetUserId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  public void setUserIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __USERID_ISSET_ID, value);
  }

  public int getPushNum() {
    return this.pushNum;
  }

  public ArchivesPushParam setPushNum(int pushNum) {
    this.pushNum = pushNum;
    setPushNumIsSet(true);
    return this;
  }

  public void unsetPushNum() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PUSHNUM_ISSET_ID);
  }

  /** Returns true if field pushNum is set (has been assigned a value) and false otherwise */
  public boolean isSetPushNum() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PUSHNUM_ISSET_ID);
  }

  public void setPushNumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PUSHNUM_ISSET_ID, value);
  }

  public int getPushType() {
    return this.pushType;
  }

  public ArchivesPushParam setPushType(int pushType) {
    this.pushType = pushType;
    setPushTypeIsSet(true);
    return this;
  }

  public void unsetPushType() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PUSHTYPE_ISSET_ID);
  }

  /** Returns true if field pushType is set (has been assigned a value) and false otherwise */
  public boolean isSetPushType() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PUSHTYPE_ISSET_ID);
  }

  public void setPushTypeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PUSHTYPE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_ID:
      if (value == null) {
        unsetUserId();
      } else {
        setUserId((Integer)value);
      }
      break;

    case PUSH_NUM:
      if (value == null) {
        unsetPushNum();
      } else {
        setPushNum((Integer)value);
      }
      break;

    case PUSH_TYPE:
      if (value == null) {
        unsetPushType();
      } else {
        setPushType((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_ID:
      return getUserId();

    case PUSH_NUM:
      return getPushNum();

    case PUSH_TYPE:
      return getPushType();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_ID:
      return isSetUserId();
    case PUSH_NUM:
      return isSetPushNum();
    case PUSH_TYPE:
      return isSetPushType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ArchivesPushParam)
      return this.equals((ArchivesPushParam)that);
    return false;
  }

  public boolean equals(ArchivesPushParam that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_userId = true;
    boolean that_present_userId = true;
    if (this_present_userId || that_present_userId) {
      if (!(this_present_userId && that_present_userId))
        return false;
      if (this.userId != that.userId)
        return false;
    }

    boolean this_present_pushNum = true;
    boolean that_present_pushNum = true;
    if (this_present_pushNum || that_present_pushNum) {
      if (!(this_present_pushNum && that_present_pushNum))
        return false;
      if (this.pushNum != that.pushNum)
        return false;
    }

    boolean this_present_pushType = true;
    boolean that_present_pushType = true;
    if (this_present_pushType || that_present_pushType) {
      if (!(this_present_pushType && that_present_pushType))
        return false;
      if (this.pushType != that.pushType)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + userId;

    hashCode = hashCode * 8191 + pushNum;

    hashCode = hashCode * 8191 + pushType;

    return hashCode;
  }

  @Override
  public int compareTo(ArchivesPushParam other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUserId()).compareTo(other.isSetUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userId, other.userId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPushNum()).compareTo(other.isSetPushNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPushNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pushNum, other.pushNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPushType()).compareTo(other.isSetPushType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPushType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pushType, other.pushType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ArchivesPushParam(");
    boolean first = true;

    sb.append("userId:");
    sb.append(this.userId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pushNum:");
    sb.append(this.pushNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pushType:");
    sb.append(this.pushType);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'userId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'pushNum' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'pushType' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ArchivesPushParamStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ArchivesPushParamStandardScheme getScheme() {
      return new ArchivesPushParamStandardScheme();
    }
  }

  private static class ArchivesPushParamStandardScheme extends org.apache.thrift.scheme.StandardScheme<ArchivesPushParam> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ArchivesPushParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userId = iprot.readI32();
              struct.setUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PUSH_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pushNum = iprot.readI32();
              struct.setPushNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PUSH_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pushType = iprot.readI32();
              struct.setPushTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetUserId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'userId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetPushNum()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pushNum' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetPushType()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pushType' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ArchivesPushParam struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(USER_ID_FIELD_DESC);
      oprot.writeI32(struct.userId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PUSH_NUM_FIELD_DESC);
      oprot.writeI32(struct.pushNum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PUSH_TYPE_FIELD_DESC);
      oprot.writeI32(struct.pushType);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ArchivesPushParamTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ArchivesPushParamTupleScheme getScheme() {
      return new ArchivesPushParamTupleScheme();
    }
  }

  private static class ArchivesPushParamTupleScheme extends org.apache.thrift.scheme.TupleScheme<ArchivesPushParam> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ArchivesPushParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.userId);
      oprot.writeI32(struct.pushNum);
      oprot.writeI32(struct.pushType);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ArchivesPushParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.userId = iprot.readI32();
      struct.setUserIdIsSet(true);
      struct.pushNum = iprot.readI32();
      struct.setPushNumIsSet(true);
      struct.pushType = iprot.readI32();
      struct.setPushTypeIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

