spring:
  application:
    name: beebee-archives-thrift-consumer
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@172.16.9.232:8761/eureka
  instance:
    prefer-ip-address: true
beebee-archives-thrift-consumer: # 服务提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

---
server:
  port: 10111
spring:
  profiles: archives-consumer1
---
server:
  port: 10112
spring:
  profiles: archives-consumer2
---
server:
  port: 10113
spring:
  profiles: archives-consumer3