#spring:
#  profiles:
#    active: test  # 环境 dev|test|pro



# 正式服务器 ------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: beebee-common-service-thrift-consumer
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@172.16.9.232:8761/eureka
  instance:
    prefer-ip-address: true
beebee-common-service-thrift-consumer: # 服务提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

---
server:
  port: 9711
spring:
  profiles: common-consumer1
---
server:
  port: 9712
spring:
  profiles: common-consumer2
---
server:
  port: 9713
spring:
  profiles: common-consumer3