spring:
  application:
    name: beebee-third-service-thrift-provider-client

server:
  port: 8721

thrift:
  server:
    host: localhost
    port: 8741

# 禁止自动注册eureka，仅dev模式使用
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false