#spring:
#  profiles:
#    active: test  # 环境 dev|test|pro



# 正式服务器 ------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: beebee-topic-thrift-consumer
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@172.16.9.232:8761/eureka
  instance:
    prefer-ip-address: true
beebee-topic-thrift-consumer: # 服务提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

---
server:
  port: 10211
spring:
  profiles: topic-consumer1
---
server:
  port: 10212
spring:
  profiles: topic-consumer2
---
server:
  port: 10213
spring:
  profiles: topic-consumer3