spring:
  application:
    name: beebee-common-service-thrift-provider-client

server:
  port: 9721

thrift:
  server:
    host: localhost
    port: 9741

# 禁止自动注册eureka，仅dev模式使用
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false