/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.quwan.beebee.resp.archives;

import java.util.List;

public class CommentListResp {
  
  private Integer commentId; 
  private Integer userId; 
  private String username; 
  private String content; 
  private String addTime; 
  private String nickname;
  private String head;
  private List<CommentAnswerResp> commentAnswerList;

  public Integer getCommentId() {
    return commentId;
  }

  public void setCommentId(Integer commentId) {
    this.commentId = commentId;
  }

  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public String getAddTime() {
    return addTime;
  }

  public void setAddTime(String addTime) {
    this.addTime = addTime;
  }

  public String getNickname() {
    return nickname;
  }

  /* 如果昵称为空，则用mobile */
  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public String getHead() {
    return head;
  }

  public void setHead(String head) {
    this.head = head;
  }

  public List<CommentAnswerResp> getCommentAnswerList() {
    return commentAnswerList;
  }

  public void setCommentAnswerList(List<CommentAnswerResp> commentAnswerList) {
    this.commentAnswerList = commentAnswerList;
  }

  @Override
  public String toString() {
    return "CommentListResp{" +
            "commentId=" + commentId +
            ", userId=" + userId +
            ", username='" + username + '\'' +
            ", content='" + content + '\'' +
            ", addTime='" + addTime + '\'' +
            ", nickname='" + nickname + '\'' +
            ", head='" + head + '\'' +
            ", commentAnswerList=" + commentAnswerList +
            '}';
  }
}