/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.quwan.beebee.param.user;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-02-01")
public class GetCommentsByUserIdentityParam implements org.apache.thrift.TBase<GetCommentsByUserIdentityParam, GetCommentsByUserIdentityParam._Fields>, java.io.Serializable, Cloneable, Comparable<GetCommentsByUserIdentityParam> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetCommentsByUserIdentityParam");

  private static final org.apache.thrift.protocol.TField TARGET_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("targetUserId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField IDENTITY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("identityId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField PAGE_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("pageNumber", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField PAGE_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("pageSize", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GetCommentsByUserIdentityParamStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GetCommentsByUserIdentityParamTupleSchemeFactory();

  public int targetUserId; // required
  public int identityId; // required
  public int pageNumber; // required
  public int pageSize; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TARGET_USER_ID((short)1, "targetUserId"),
    IDENTITY_ID((short)2, "identityId"),
    PAGE_NUMBER((short)3, "pageNumber"),
    PAGE_SIZE((short)4, "pageSize");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TARGET_USER_ID
          return TARGET_USER_ID;
        case 2: // IDENTITY_ID
          return IDENTITY_ID;
        case 3: // PAGE_NUMBER
          return PAGE_NUMBER;
        case 4: // PAGE_SIZE
          return PAGE_SIZE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TARGETUSERID_ISSET_ID = 0;
  private static final int __IDENTITYID_ISSET_ID = 1;
  private static final int __PAGENUMBER_ISSET_ID = 2;
  private static final int __PAGESIZE_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TARGET_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("targetUserId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IDENTITY_ID, new org.apache.thrift.meta_data.FieldMetaData("identityId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PAGE_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("pageNumber", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PAGE_SIZE, new org.apache.thrift.meta_data.FieldMetaData("pageSize", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetCommentsByUserIdentityParam.class, metaDataMap);
  }

  public GetCommentsByUserIdentityParam() {
  }

  public GetCommentsByUserIdentityParam(
    int targetUserId,
    int identityId,
    int pageNumber,
    int pageSize)
  {
    this();
    this.targetUserId = targetUserId;
    setTargetUserIdIsSet(true);
    this.identityId = identityId;
    setIdentityIdIsSet(true);
    this.pageNumber = pageNumber;
    setPageNumberIsSet(true);
    this.pageSize = pageSize;
    setPageSizeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetCommentsByUserIdentityParam(GetCommentsByUserIdentityParam other) {
    __isset_bitfield = other.__isset_bitfield;
    this.targetUserId = other.targetUserId;
    this.identityId = other.identityId;
    this.pageNumber = other.pageNumber;
    this.pageSize = other.pageSize;
  }

  public GetCommentsByUserIdentityParam deepCopy() {
    return new GetCommentsByUserIdentityParam(this);
  }

  @Override
  public void clear() {
    setTargetUserIdIsSet(false);
    this.targetUserId = 0;
    setIdentityIdIsSet(false);
    this.identityId = 0;
    setPageNumberIsSet(false);
    this.pageNumber = 0;
    setPageSizeIsSet(false);
    this.pageSize = 0;
  }

  public int getTargetUserId() {
    return this.targetUserId;
  }

  public GetCommentsByUserIdentityParam setTargetUserId(int targetUserId) {
    this.targetUserId = targetUserId;
    setTargetUserIdIsSet(true);
    return this;
  }

  public void unsetTargetUserId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TARGETUSERID_ISSET_ID);
  }

  /** Returns true if field targetUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetUserId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TARGETUSERID_ISSET_ID);
  }

  public void setTargetUserIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TARGETUSERID_ISSET_ID, value);
  }

  public int getIdentityId() {
    return this.identityId;
  }

  public GetCommentsByUserIdentityParam setIdentityId(int identityId) {
    this.identityId = identityId;
    setIdentityIdIsSet(true);
    return this;
  }

  public void unsetIdentityId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IDENTITYID_ISSET_ID);
  }

  /** Returns true if field identityId is set (has been assigned a value) and false otherwise */
  public boolean isSetIdentityId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IDENTITYID_ISSET_ID);
  }

  public void setIdentityIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IDENTITYID_ISSET_ID, value);
  }

  public int getPageNumber() {
    return this.pageNumber;
  }

  public GetCommentsByUserIdentityParam setPageNumber(int pageNumber) {
    this.pageNumber = pageNumber;
    setPageNumberIsSet(true);
    return this;
  }

  public void unsetPageNumber() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PAGENUMBER_ISSET_ID);
  }

  /** Returns true if field pageNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetPageNumber() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PAGENUMBER_ISSET_ID);
  }

  public void setPageNumberIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PAGENUMBER_ISSET_ID, value);
  }

  public int getPageSize() {
    return this.pageSize;
  }

  public GetCommentsByUserIdentityParam setPageSize(int pageSize) {
    this.pageSize = pageSize;
    setPageSizeIsSet(true);
    return this;
  }

  public void unsetPageSize() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PAGESIZE_ISSET_ID);
  }

  /** Returns true if field pageSize is set (has been assigned a value) and false otherwise */
  public boolean isSetPageSize() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PAGESIZE_ISSET_ID);
  }

  public void setPageSizeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PAGESIZE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case TARGET_USER_ID:
      if (value == null) {
        unsetTargetUserId();
      } else {
        setTargetUserId((java.lang.Integer)value);
      }
      break;

    case IDENTITY_ID:
      if (value == null) {
        unsetIdentityId();
      } else {
        setIdentityId((java.lang.Integer)value);
      }
      break;

    case PAGE_NUMBER:
      if (value == null) {
        unsetPageNumber();
      } else {
        setPageNumber((java.lang.Integer)value);
      }
      break;

    case PAGE_SIZE:
      if (value == null) {
        unsetPageSize();
      } else {
        setPageSize((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TARGET_USER_ID:
      return getTargetUserId();

    case IDENTITY_ID:
      return getIdentityId();

    case PAGE_NUMBER:
      return getPageNumber();

    case PAGE_SIZE:
      return getPageSize();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TARGET_USER_ID:
      return isSetTargetUserId();
    case IDENTITY_ID:
      return isSetIdentityId();
    case PAGE_NUMBER:
      return isSetPageNumber();
    case PAGE_SIZE:
      return isSetPageSize();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof GetCommentsByUserIdentityParam)
      return this.equals((GetCommentsByUserIdentityParam)that);
    return false;
  }

  public boolean equals(GetCommentsByUserIdentityParam that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_targetUserId = true;
    boolean that_present_targetUserId = true;
    if (this_present_targetUserId || that_present_targetUserId) {
      if (!(this_present_targetUserId && that_present_targetUserId))
        return false;
      if (this.targetUserId != that.targetUserId)
        return false;
    }

    boolean this_present_identityId = true;
    boolean that_present_identityId = true;
    if (this_present_identityId || that_present_identityId) {
      if (!(this_present_identityId && that_present_identityId))
        return false;
      if (this.identityId != that.identityId)
        return false;
    }

    boolean this_present_pageNumber = true;
    boolean that_present_pageNumber = true;
    if (this_present_pageNumber || that_present_pageNumber) {
      if (!(this_present_pageNumber && that_present_pageNumber))
        return false;
      if (this.pageNumber != that.pageNumber)
        return false;
    }

    boolean this_present_pageSize = true;
    boolean that_present_pageSize = true;
    if (this_present_pageSize || that_present_pageSize) {
      if (!(this_present_pageSize && that_present_pageSize))
        return false;
      if (this.pageSize != that.pageSize)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + targetUserId;

    hashCode = hashCode * 8191 + identityId;

    hashCode = hashCode * 8191 + pageNumber;

    hashCode = hashCode * 8191 + pageSize;

    return hashCode;
  }

  @Override
  public int compareTo(GetCommentsByUserIdentityParam other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTargetUserId()).compareTo(other.isSetTargetUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetUserId, other.targetUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIdentityId()).compareTo(other.isSetIdentityId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdentityId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.identityId, other.identityId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPageNumber()).compareTo(other.isSetPageNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPageNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pageNumber, other.pageNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPageSize()).compareTo(other.isSetPageSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPageSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pageSize, other.pageSize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("GetCommentsByUserIdentityParam(");
    boolean first = true;

    sb.append("targetUserId:");
    sb.append(this.targetUserId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("identityId:");
    sb.append(this.identityId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pageNumber:");
    sb.append(this.pageNumber);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pageSize:");
    sb.append(this.pageSize);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'targetUserId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'identityId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'pageNumber' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'pageSize' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetCommentsByUserIdentityParamStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public GetCommentsByUserIdentityParamStandardScheme getScheme() {
      return new GetCommentsByUserIdentityParamStandardScheme();
    }
  }

  private static class GetCommentsByUserIdentityParamStandardScheme extends org.apache.thrift.scheme.StandardScheme<GetCommentsByUserIdentityParam> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetCommentsByUserIdentityParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TARGET_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.targetUserId = iprot.readI32();
              struct.setTargetUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // IDENTITY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.identityId = iprot.readI32();
              struct.setIdentityIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PAGE_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pageNumber = iprot.readI32();
              struct.setPageNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PAGE_SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pageSize = iprot.readI32();
              struct.setPageSizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTargetUserId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'targetUserId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetIdentityId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'identityId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetPageNumber()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pageNumber' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetPageSize()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pageSize' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetCommentsByUserIdentityParam struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TARGET_USER_ID_FIELD_DESC);
      oprot.writeI32(struct.targetUserId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IDENTITY_ID_FIELD_DESC);
      oprot.writeI32(struct.identityId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PAGE_NUMBER_FIELD_DESC);
      oprot.writeI32(struct.pageNumber);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PAGE_SIZE_FIELD_DESC);
      oprot.writeI32(struct.pageSize);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetCommentsByUserIdentityParamTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public GetCommentsByUserIdentityParamTupleScheme getScheme() {
      return new GetCommentsByUserIdentityParamTupleScheme();
    }
  }

  private static class GetCommentsByUserIdentityParamTupleScheme extends org.apache.thrift.scheme.TupleScheme<GetCommentsByUserIdentityParam> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetCommentsByUserIdentityParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.targetUserId);
      oprot.writeI32(struct.identityId);
      oprot.writeI32(struct.pageNumber);
      oprot.writeI32(struct.pageSize);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetCommentsByUserIdentityParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.targetUserId = iprot.readI32();
      struct.setTargetUserIdIsSet(true);
      struct.identityId = iprot.readI32();
      struct.setIdentityIdIsSet(true);
      struct.pageNumber = iprot.readI32();
      struct.setPageNumberIsSet(true);
      struct.pageSize = iprot.readI32();
      struct.setPageSizeIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

