#spring:
#  profiles:
#    active: test # 环境 dev|test|pro



# 本地测试 --------------------------------------------------------------------------------------------------------------
#spring:
#  application:
#    name: beebee-archives-thrift-provider-client
#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://user:password123@localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#beebee-archives-thrift-provider-client: # 服务提供者的名称
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
#---
#server:
#  port: 10121
#thrift:
#  server:
#    host: localhost
#    port: 10141
#spring:
#  profiles: archives-client1
#---
#server:
#  port: 10122
#thrift:
#  server:
#    host: localhost
#    port: 10142
#spring:
#  profiles: archives-client2
#---
#server:
#  port: 10123
#thrift:
#  server:
#    host: localhost
#    port: 10143
#spring:
#  profiles: archives-client3



# 正式服务器 -------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: beebee-archives-thrift-provider-client
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@172.16.9.232:8761/eureka
  instance:
    prefer-ip-address: true
beebee-archives-thrift-provider-client: # 服务提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

---
server:
  port: 10121
thrift:
  server:
    host: localhost
    port: 10141
spring:
  profiles: archives-client1
---
server:
  port: 10122
thrift:
  server:
    host: localhost
    port: 10142
spring:
  profiles: archives-client2
---
server:
  port: 10123
thrift:
  server:
    host: localhost
    port: 10143
spring:
  profiles: archives-client3