spring:
  application:
    name: beebee-user-thrift-provider-client

server:
  port: 10321

thrift:
  server:
    host: localhost
    port: 10341

# 禁止自动注册eureka，仅dev模式使用
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false