#spring:
#  profiles:
#    active: test # 环境 dev|test|pro



# 正式服务器 ------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: beebee-user-thrift-provider-client
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@172.16.9.232:8761/eureka
  instance:
    prefer-ip-address: true
beebee-user-thrift-provider-client: # 服务提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

---
server:
  port: 10321
thrift:
  server:
    host: localhost
    port: 10341
spring:
  profiles: user-client1
---
server:
  port: 10322
thrift:
  server:
    host: localhost
    port: 10342
spring:
  profiles: user-client2
---
server:
  port: 10323
thrift:
  server:
    host: localhost
    port: 10343
spring:
  profiles: user-client3