spring:
  application:
    name: beebee-user-thrift-provider-client
server:
  port: 10321
thrift:
  server:
    host: 172.17.2.174
    port: 10341
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@172.17.2.172:8761/eureka
  instance:
    prefer-ip-address: true
beebee-user-thrift-provider-client: # 服务提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule